server:
  replicaCount: 1
  image:
    tag: 1.28.0
  config:
    numHistoryShards: 1024
    persistence:
      default:
        driver: "sql"
        sql:
          driver: "postgres12"
          host: postgresql.default.svc.cluster.local
          port: 5432
          database: temporal_persistence_2
          user: temporal
          password: temporal
          maxConns: 20
          maxIdleConns: 20
          maxConnLifetime: "1h"
      visibility:
        driver: "sql"
        sql:
          driver: "postgres12"
          host: postgresql.default.svc.cluster.local
          port: 5432
          database: temporal_visibility_2
          user: temporal
          password: temporal
          maxConns: 20
          maxIdleConns: 20
          maxConnLifetime: "1h"
    clusterMetadata:
      enableGlobalNamespace: true
      failoverVersionIncrement: 10
      masterClusterName: "cluster-1"
      currentClusterName: "cluster-2"
      clusterInformation:
        cluster-1:
          enabled: true
          initialFailoverVersion: 1
          rpcAddress: "cluster-1-temporal-frontend:7233"
        cluster-2:
          enabled: true
          initialFailoverVersion: 2
          rpcAddress: "cluster-2-temporal-frontend:7233"
  frontend:
    service:
      type: NodePort
      port: 7233
      httpPort: 7243
      targetPort: 7233
      nodePort: 31233

admintools:
  additionalEnv:
    - name: SQL_USER
      value: postgres

web:
  service:
    type: NodePort
    port: 8080
    targetPort: 8080
    nodePort: 31080

cassandra:
  enabled: false
elasticsearch:
  enabled: false

grafana:
  enabled: false

prometheus:
  enabled: false
